name: ycyw
services:
  ycyw-front:
    build:
      context: ./ycyw-front
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - type: bind
        source: ./ycyw-front
        target: /app
      - type: volume
        target: /app/node_modules
  ycyw-back:
    build:
      context: ./ycyw-back
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ycyw
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ycyw" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - ycyw-front
      - ycyw-back
      - db
